baseURL = 'https://patrick-salazar.github.io/Portfolio/'
languageCode = 'en-us'
title = 'Patrick Salazar'
theme = 'PaperMod'

[params]
  author = "Patrick Salazar"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  defaultTheme = "light"
  disableThemeToggle = false

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3
